"""
Questions du quiz Performance Ultime
Basees strictement sur le transcript video Achzod
"""

QUESTIONS = [
    {"id":1,"question":"Combien de seances intenses maximum par semaine Achzod recommande pour quelqu'un de plus de 27-28 ans ?","options":["5 a 6","3 a 4","2","7"],"correct":1,"explanation":"Achzod recommande 3 a 4 entrainements intenses maximum par semaine pour les personnes avec des objectifs professionnels et familiaux."},
    {"id":2,"question":"Que signifie HRV ?","options":["High Recovery Volume","Heart Rate Variability (Variabilite de la frequence cardiaque)","Hormonal Response Value","Hypertrophy Recovery Vector"],"correct":1,"explanation":"HRV signifie Heart Rate Variability, la variabilite de la frequence cardiaque."},
    {"id":3,"question":"Que mesure la HRV exactement ?","options":["Le nombre de battements par minute","La pression arterielle","La variabilite temporelle entre deux battements du coeur en millisecondes","Le taux d'oxygene dans le sang"],"correct":2,"explanation":"La HRV mesure la variation temporelle entre deux battements de votre coeur en millisecondes."},
    {"id":4,"question":"Une HRV elevee signifie une dominance de quel systeme ?","options":["Systeme sympathique","Systeme parasympathique","Systeme endocrinien","Systeme lymphatique"],"correct":1,"explanation":"Une HRV elevee signifie une dominance parasympathique, c'est un bon score de recuperation."},
    {"id":5,"question":"Quel mineral Achzod considere comme le plus important ?","options":["Le zinc","Le calcium","Le magnesium","Le fer"],"correct":2,"explanation":"Pour Achzod, le magnesium est le mineral le plus important apres ses annees de recherche et d'experience."},
    {"id":6,"question":"Qu'est-ce que l'ATP ?","options":["Une hormone anabolique","La monnaie energetique universelle du corps","Un neurotransmetteur","Un acide amine"],"correct":1,"explanation":"L'ATP (adenosine triphosphate) est la monnaie energetique universelle de chaque corps humain."},
    {"id":7,"question":"Quelle enzyme a besoin de magnesium pour produire l'ATP ?","options":["La lipase","L'ATP synthase","La trypsine","La lactase"],"correct":1,"explanation":"L'ATP synthase est l'enzyme cle qui ne peut pas fonctionner sans magnesium."},
    {"id":8,"question":"Quand le cortisol monte, qu'utilise le corps pour calmer la reponse ?","options":["Du calcium","De la creatine","Du magnesium","Du fer"],"correct":2,"explanation":"Le corps utilise du magnesium pour calmer la reponse adrenalergique provoquee par le cortisol."},
    {"id":9,"question":"Quel est le cercle vicieux du magnesium ?","options":["Plus de magnesium = plus de cortisol","Plus de cortisol = plus de magnesium brule = moins tolerant au stress = plus de cortisol","Moins de cortisol = moins de magnesium","Le magnesium n'a aucun lien avec le cortisol"],"correct":1,"explanation":"Plus vous produisez du cortisol, plus vous brulez du magnesium. Deficient en magnesium, votre corps produit plus de cortisol."},
    {"id":10,"question":"Que fait l'enzyme COMT ?","options":["Elle produit de la testosterone","Elle metabolise les oestrogenes et la dopamine","Elle degrade les proteines","Elle convertit le glucose en glycogene"],"correct":1,"explanation":"La COMT (catechol-O-methyltransferase) metabolise les oestrogenes et la dopamine."},
    {"id":11,"question":"Pourquoi une dopamine elevee le soir empeche de dormir ?","options":["La dopamine detruit la melatonine","Le cerveau tourne a plein regime, on cogite, on ne peut pas s'endormir","La dopamine augmente la temperature corporelle","La dopamine bloque la respiration"],"correct":1,"explanation":"Si l'enzyme COMT ne fonctionne pas bien, on ne degrade pas la dopamine. On est allonge dans son lit mais le cerveau tourne a plein regime."},
    {"id":12,"question":"L'enzyme COMT a besoin de quoi pour fonctionner ?","options":["De vitamine C","De zinc","De magnesium","De fer"],"correct":2,"explanation":"La COMT est une enzyme magnesiodependante. Sans magnesium, elle ne fonctionne pas."},
    {"id":13,"question":"Quel est le role de la serotonine dans le sommeil ?","options":["Elle vous endort directement","Elle vous prepare a l'endormissement et se convertit en melatonine","Elle bloque le cortisol","Elle augmente la GH"],"correct":1,"explanation":"La serotonine est le neurotransmetteur qui vous prepare a l'endormissement, qui vous met dans un etat de calme. Elle se convertit ensuite en melatonine."},
    {"id":14,"question":"Quel est le vrai role de la melatonine ?","options":["Elle vous endort","Elle vous garde endormi","Elle degrade le cortisol","Elle produit de la GH"],"correct":1,"explanation":"La melatonine n'est pas l'hormone qui vous endort, c'est l'hormone qui vous garde endormi."},
    {"id":15,"question":"Pourquoi la melatonine exogene ne fonctionne souvent pas toute la nuit ?","options":["Le dosage est trop faible","Elle est metabolisee rapidement par le foie en 2-3 heures","Le corps y devient resistant","Elle ne traverse pas la barriere hematoencephalique"],"correct":1,"explanation":"La melatonine exogene est metabolisee rapidement par le foie en 2-3 heures, et le corps n'a pas de reserve interne."},
    {"id":16,"question":"Quel acide amine essentiel est le precurseur de la serotonine ?","options":["La leucine","La glutamine","Le tryptophane","La tyrosine"],"correct":2,"explanation":"Le tryptophane est un acide amine essentiel qui traverse la barriere hematoencephalique et se convertit en serotonine."},
    {"id":17,"question":"Comment l'insuline aide le tryptophane a atteindre le cerveau ?","options":["Elle detruit les autres acides amines","Elle transporte les autres acides amines vers les muscles, laissant la voie libre au tryptophane","Elle augmente la permeabilite cerebrale","Elle n'a aucun lien avec le tryptophane"],"correct":1,"explanation":"L'insuline transporte les acides amines vers les muscles mais pas le tryptophane, qui se retrouve avec une autoroute libre vers le cerveau."},
    {"id":18,"question":"Quelle collation du soir Achzod recommande pour favoriser le sommeil ?","options":["Un shaker de whey","Fromage blanc, miel brut et chocolat noir 85-90%","Des pates completes","Un fruit seul"],"correct":1,"explanation":"Un petit bol de fromage blanc 0%, une cuillere a soupe de miel brut et un peu de chocolat noir 85-90%."},
    {"id":19,"question":"Quelle forme de magnesium est la plus recommandee pour le sommeil ?","options":["L'oxyde de magnesium","Le magnesium bisglycinate","Le sulfate de magnesium","Le carbonate de magnesium"],"correct":1,"explanation":"Le magnesium bisglycinate est attache a deux molecules de glycine qui activent les recepteurs GABA et calment le cerveau."},
    {"id":20,"question":"A quoi sert la glycine dans le magnesium bisglycinate ?","options":["Elle augmente la force musculaire","C'est un neurotransmetteur inhibiteur qui active les recepteurs GABA","Elle ameliore la digestion","Elle booste la testosterone"],"correct":1,"explanation":"La glycine est un neurotransmetteur inhibiteur qui active les recepteurs GABA, le neurotransmetteur principal qui calme le cerveau."},
    {"id":21,"question":"Quel marqueur sanguin indirect permet de detecter une deficience en magnesium ?","options":["La ferritine","La phosphatase alcaline (ALP)","La creatinine","L'hemoglobine"],"correct":1,"explanation":"La phosphatase alcaline (ALP) est une enzyme qui a besoin de magnesium pour fonctionner. Si inferieure a 70, deficience probable."},
    {"id":22,"question":"Si l'ALP est inferieur a combien, on est probablement deficient en magnesium ?","options":["100","70","50","30"],"correct":1,"explanation":"Si le score de votre ALP est inferieur a 70, vous etes tres probablement deficient en magnesium."},
    {"id":23,"question":"Quel dosage de magnesium elementaire Achzod recommande pour un sportif ?","options":["50 a 100 mg","300 a 500 mg","1000 mg","10 mg"],"correct":1,"explanation":"Idealement pour un bon sportif, on parle de 300 a 500 mg de magnesium elementaire."},
    {"id":24,"question":"Quel pourcentage de magnesium elementaire contient le bisglycinate ?","options":["50%","30%","10 a 11%","1%"],"correct":2,"explanation":"Le magnesium bisglycinate contient environ 10 a 11% de magnesium elementaire."},
    {"id":25,"question":"Ou est produite l'hormone de croissance (GH) ?","options":["Les glandes surrenales","La glande hypophysaire (pituitaire)","La thyroide","Le pancreas"],"correct":1,"explanation":"L'hormone de croissance est produite par la glande hypophysaire situee a la base du cerveau."},
    {"id":26,"question":"A quel moment la GH est-elle principalement secretee ?","options":["Pendant l'entrainement","Pendant le sommeil profond, entre 22h et 2h du matin","Apres le repas","Au reveil"],"correct":1,"explanation":"La GH est liberee par pulse principalement pendant le sommeil profond entre 22h et 2h du matin."},
    {"id":27,"question":"Quelle hormone bloque la secretion de GH ?","options":["La testosterone","Le cortisol","L'insuline","La dopamine"],"correct":2,"explanation":"L'insuline bloque la GH. L'insuline et la GH sont deux hormones antagonistes."},
    {"id":28,"question":"Quel est le meilleur moment pour injecter la GH exogene selon Achzod ?","options":["Le matin a jeun","Juste avant de dormir","Apres l'entrainement","Avant le repas du midi"],"correct":1,"explanation":"La strategie basique efficace est d'injecter la GH juste avant de dormir pour chevaucher la production naturelle."},
    {"id":29,"question":"Combien de temps met la GH exogene injectee a atteindre son pic ?","options":["15 minutes","2 a 3 heures","30 minutes","6 heures"],"correct":1,"explanation":"La GH sous-cutanee met 2 a 3 heures a atteindre son pic."},
    {"id":30,"question":"Pourquoi le cardio a jeun a 6h du matin juste apres injection de GH est un mythe ?","options":["Le cardio annule la GH","La GH n'est pas encore active, elle met 2-3h pour atteindre son pic","Le matin le cortisol est trop haut","La GH ne fonctionne pas le matin"],"correct":1,"explanation":"La GH met 2 a 3 heures pour atteindre son pic. Si injectee a 6h et cardio a 6h30, elle ne fait rien."},
    {"id":31,"question":"Quel secretalogue est considere comme le plus safe ?","options":["L'hexareline","Le GHRP-2","L'ipamoreline","Le CJC-1295 avec DAC"],"correct":2,"explanation":"L'ipamoreline est le plus apprecie car c'est le plus safe avec le moins d'effets secondaires, il stimule presque pas la prolactine."},
    {"id":32,"question":"Qu'est-ce que la biogenese mitochondriale ?","options":["La destruction des mitochondries","La fabrication de nouvelles mitochondries par les cellules","La fusion des cellules musculaires","Le stockage des graisses"],"correct":1,"explanation":"La biogenese mitochondriale, c'est quand les cellules fabriquent de nouvelles mitochondries."},
    {"id":33,"question":"Comment s'appelle le processus de combustion des acides gras ?","options":["La glycolyse","La beta-oxydation","La gluconeogenese","La cetogenese"],"correct":1,"explanation":"Le processus pour bruler des acides gras s'appelle la beta-oxydation."},
    {"id":34,"question":"La glycolyse anaerobie produit combien de molecules d'ATP par glucose ?","options":["30 a 35","10 a 15","2","50"],"correct":2,"explanation":"La glycolyse anaerobie produit seulement 2 molecules d'ATP par glucose, c'est assez inefficace."},
    {"id":35,"question":"La phosphorylation oxydative produit combien de molecules d'ATP ?","options":["2","10","30 a 35","100"],"correct":2,"explanation":"La phosphorylation oxydative produit 30 a 35 molecules d'ATP, environ 15 a 17 fois superieur a la glycolyse anaerobie."},
    {"id":36,"question":"La vitamine D est en realite quoi ?","options":["Un acide amine","Une hormone steroidienne","Un electrolyte","Un enzyme"],"correct":1,"explanation":"La vitamine D n'est pas vraiment une vitamine, c'est plutot une hormone steroidienne."},
    {"id":37,"question":"Combien de genes la vitamine D module-t-elle dans le corps ?","options":["200","500","Plus de 2000","50"],"correct":2,"explanation":"La vitamine D module plus de 2000 genes dans votre corps."},
    {"id":38,"question":"Qu'est-ce que la somatostatine ?","options":["Un peptide anabolique","L'hormone qui stoppe la secretion de GH","Un neurotransmetteur du bonheur","Un type de creatine"],"correct":1,"explanation":"La somatostatine est l'hormone qui stoppe la secretion de GH apres 3-4 heures."},
    {"id":39,"question":"Combien de jours de repos de suite Achzod recommande pour certains profils ?","options":["1 jour","2 jours de suite","3 jours","0, jamais de repos"],"correct":1,"explanation":"Achzod recommande 2 jours de repos de suite, notamment pour les personnes avec testo basse, hypothyroidie ou metabolisme tres rapide."},
    {"id":40,"question":"Pour ceux qui n'arrivent pas a maigrir malgre deficit, cardio et bon sommeil, ou est probablement le probleme ?","options":["Les muscles","Les mitochondries qui ne fonctionnent pas normalement","Le systeme digestif","Le systeme immunitaire"],"correct":1,"explanation":"Le probleme vient des mitochondries qui n'arrivent pas a travailler normalement et donc a switcher vers la beta-oxydation."},
]


def get_all_questions():
    return QUESTIONS


def get_question_by_id(question_id: int):
    for q in QUESTIONS:
        if q["id"] == question_id:
            return q
    return None
